language: node_js
node_js:
  - "0.12"
  - "0.10"
env:
  - NODE_ENV=production
before_script:
  - npm install --production=false
  - npm install -g bower
  - npm install -g gulp
  - bower install
script: gulp test
after_success: gulp pack
addons:
  artifacts:
    paths:
      - $(ls $TRAVIS_BUILD_DIR/dist/*.tar.gz)
